"use server";

import { revalidatePath } from "next/cache";
import { createClient as createServerClient } from "@/lib/supabase/server";
import { uploadToSupabaseStorage } from "./storage";

export async function submitMemberCard(formData: FormData) {
  const supabase = await createServerClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) return { error: "Silakan login terlebih dahulu" };

  const { data: member } = await supabase
    .from("members")
    .select("id")
    .eq("auth_id", user.id)
    .single();

  if (!member) return { error: "Data member tidak ditemukan" };

  // Prepare card data
  const cardData: any = {
    user_id: user.id, // member_cards.user_id references auth.users(id)
    full_name: formData.get("fullName") as string,
    nickname: formData.get("nickname") as string || null,
    phone: formData.get("phone") as string,
    family_count: parseInt(formData.get("familyCount") as string) || 1,
    gender: formData.get("gender") as string || null,
    birth_place: formData.get("birthPlace") as string || null,
    birth_date: formData.get("birthDate") as string || null,
    religion: formData.get("religion") as string || null,
    nik: formData.get("nik") as string || null,
    npwp: formData.get("npwp") as string || null,
    email: formData.get("email") as string || user.email || null,
    address: formData.get("address") as string || null,
    postal_code: formData.get("postalCode") as string || null,
    education: formData.get("education") as string || null,
    occupation: formData.get("occupation") as string || null,
    experience: formData.get("experience") as string || null,
    motivation: formData.get("motivation") as string || null,
    photo_url: formData.get("existingPhotoUrl") as string || null,
    signature_url: formData.get("existingSignatureUrl") as string || null,
    status: "pending",
  };

  // Handle arrays (JSON strings from form)
  try {
    const interests = formData.get("interests");
    if (interests) cardData.interests = JSON.parse(interests as string);
  } catch {}
  try {
    const skills = formData.get("skills");
    if (skills) cardData.skills = JSON.parse(skills as string);
  } catch {}

  // Handle photo upload
  const photoFile = formData.get("photo") as File | null;
  if (photoFile && photoFile.size > 0 && photoFile.name) {
    try {
      const ext = photoFile.name.split(".").pop() || "jpg";
      const photoPath = `${user.id}/photo_${Date.now()}.${ext}`;
      cardData.photo_url = await uploadToSupabaseStorage("member-cards", photoPath, photoFile);
    } catch (err) {
      console.error("Photo upload error:", err);
    }
  }

  // Handle signature (data URL → blob → upload)
  const signatureDataUrl = formData.get("signature") as string;
  if (signatureDataUrl && signatureDataUrl.startsWith("data:image")) {
    try {
      const blob = Buffer.from(signatureDataUrl.split(",")[1], "base64");
      const file = new File([blob], "signature.png", { type: "image/png" });
      const sigPath = `${user.id}/signature_${Date.now()}.png`;
      cardData.signature_url = await uploadToSupabaseStorage("member-cards", sigPath, file);
    } catch (err) {
      console.error("Signature upload error:", err);
    }
  }

  // Check existing card to decide insert or update
  const { data: existingCard } = await supabase
    .from("member_cards")
    .select("id, status")
    .eq("user_id", user.id)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  let error;
  if (existingCard && (existingCard.status === "pending" || existingCard.status === "rejected")) {
    // Update existing card
    const result = await supabase
      .from("member_cards")
      .update(cardData)
      .eq("id", existingCard.id);
    error = result.error;
  } else {
    // Insert new card
    cardData.member_number = null; // Will be generated by admin on approval
    const result = await supabase.from("member_cards").insert(cardData);
    error = result.error;
  }

  if (error) {
    if (error.code === "23505") {
      return { error: "Anda sudah memiliki kartu anggota" };
    }
    return { error: "Gagal mendaftar kartu anggota" };
  }

  revalidatePath("/membership");
  revalidatePath("/my-member-card");
  return { success: "Pendaftaran kartu anggota berhasil" };
}

export async function getMemberCards() {
  const supabase = await createServerClient();
  const { data } = await supabase
    .from("member_cards")
    .select("*, user_id!inner(full_name, email, member_id)")
    .order("created_at", { ascending: false });

  return data ?? [];
}

export async function verifyMemberCard(id: string, status: "approved" | "rejected", rejectionReason?: string) {
  const supabase = await createServerClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) return { error: "Unauthorized" };

  const { data: admin } = await supabase
    .from("members")
    .select("id")
    .eq("auth_id", user.id)
    .single();

  const updates: any = {
    status,
    verified_by: admin?.id ?? null,
    verified_at: new Date().toISOString(),
  };

  if (rejectionReason) {
    updates.rejection_reason = rejectionReason;
  }

  const { error } = await supabase
    .from("member_cards")
    .update(updates)
    .eq("id", id);

  if (error) return { error: error.message };
  revalidatePath("/admin/member-verification");
  return { success: true };
}

export async function approveMemberCard(id: string) {
  return verifyMemberCard(id, "approved");
}

export async function rejectMemberCard(id: string, reason?: string) {
  return verifyMemberCard(id, "rejected", reason);
}

export async function checkMemberCardStatus() {
  const supabase = await createServerClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) return null;

  const { data: member } = await supabase
    .from("members")
    .select("id")
    .eq("auth_id", user.id)
    .single();

  if (!member) return null;

  const { data } = await supabase
    .from("member_cards")
    .select("*")
    .eq("user_id", member.id)
    .order("created_at", { ascending: false })
    .limit(1)
    .maybeSingle();

  return data;
}
